name: AWS Pipeline

on:
  push:
    branches:
      - main

jobs:
  tf-run:
    name: Terraform run on AWS
    runs-on: ubuntu-latest

    steps:
      # Step 01 - Checkout do Código
      - name: Step 01 - Checkout GitHub Repo
        uses: actions/checkout@v3

      # Step 02 - Configurar Credenciais AWS
      - name: Step 02 - Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 03 - Instalar Terraform
      - name: Step 03 - Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 04 - Inicializar Terraform
      - name: Step 04 - Terraform Init
        run: terraform init -chdir=terraform/ -input=false -reconfigure -upgrade
        env:
          TF_LOG: DEBUG

      # Step 05 - Validar Terraform
      - name: Step 05 - Terraform Validate
        run: terraform validate -chdir=terraform/

      # Step 06 - Planejar Terraform
      - name: Step 06 - Terraform Plan
        run: terraform plan -chdir=terraform/ -input=false -out=tfplan

      # Step 07 - Aplicar Terraform
      - name: Step 07 - Terraform Apply
        run: terraform apply -chdir=terraform/ -auto-approve tfplan
