name: Deploy Zabbix Infrastructure

on:
  push:
    branches:
      - developer

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verificar estrutura de arquivos
        run: |
          echo "Diretório atual:"
          pwd
          echo "Arquivos no diretório terraform/:"
          ls -la terraform/

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar Terraform
        run: terraform init
        env:
          TF_LOG: DEBUG

      - name: Validar Terraform
        run: terraform validate -chdir=terraform/

      - name: Aplicar Terraform
        run: terraform apply -auto-approve -chdir=terraform/
