name: Deploy Zabbix Infrastructure

on:
  push:
    branches:
      - developer

jobs:
  terraform:
    runs-on: ubuntu-latest
    # environment: production  <-- Remove this line for now

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init -chdir=terraform/
        env:
          TF_LOG: DEBUG

      - name: Validate Terraform
        run: terraform validate -chdir=terraform/

      - name: Plan Terraform
        run: terraform plan -chdir=terraform/ -out=tfplan

      - name: Apply Terraform
        run: terraform apply -chdir=terraform/ tfplan
